export const TRACKED_BASE_LIMIT_PER_GENDER = 1000;
export const DISPLAY_LIMIT_PER_GENDER = 500;
export const INVESTIGATION_RANK_PER_GENDER = 600;

export const TRACKED_BASE_TOTAL = TRACKED_BASE_LIMIT_PER_GENDER * 2;
export const DISPLAY_TOTAL = DISPLAY_LIMIT_PER_GENDER * 2;

export const EXTERNAL_CANDIDATE_FALLBACK_MARGIN = 40;

